name: CI

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:

concurrency:
  group: environment-${{ github.ref }}
  cancel-in-progress: true

jobs:
  job-common:
    runs-on: ubuntu-latest
    outputs:
      SHORT_SHA: ${{ steps.expose_sha.outputs.short_sha }}
    steps:
      - name: expose short commit sha
        id: expose_sha
        run: |
          SHORT_SHA=${GITHUB_SHA::7}
          echo "short_sha=$SHORT_SHA" >> $GITHUB_ENV
          echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_OUTPUT

  build-android:
    needs: job-common
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      SHORT_SHA: ${{ needs.job-common.outputs.SHORT_SHA }}
    outputs:
      VERSION_NAME: ${{ steps.version.outputs.VERSION_NAME }}
      VERSION_CODE: ${{ steps.version.outputs.VERSION_CODE }}
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: setup jdk 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: gradle

      - name: expose version
        id: version
        run: ./gradlew -q printVersion | tee -a $GITHUB_ENV | tee -a $GITHUB_OUTPUT

      - uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/main' }}
          cache-write: true

      - run: ./gradlew assembleDebug

      - uses: actions/upload-artifact@v4
        with:
          path: app/build/outputs/apk
          retention-days: 1

      - name: expose debug apk path
        run: latest=$(ls -t app/build/outputs/apk/*.apk | head -1); echo "APK_PATH=$latest" >> $GITHUB_ENV

      - name: send telegram message
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          THREAD_ID: ${{ secrets.TELEGRAM_THREAD_ID }}
          MESSAGE: |
            ✅ <b>${{ env.VERSION_NAME }} (${{ env.VERSION_CODE }})</b>
            <b>Ветка:</b> ${{ github.ref_name }}
            <b>Коммит:</b> <code>${{ env.SHORT_SHA }}</code>
        run: |
          curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendDocument" \
            -F chat_id="${CHAT_ID}" \
            -F document="@${{ env.APK_PATH }}" \
            -F caption="${{ env.MESSAGE }}" \
            -F message_thread_id="${THREAD_ID}" \
            -F parse_mode="HTML"