name: Distribution App

on:
  push:
    branches: [ master ]
  workflow_dispatch:
  
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  KEYSTORE_FILE: ${{ secrets.KEYSTORE_FILE }}
  KEYSTORE_KEY_ALIAS: ${{ secrets.KEYSTORE_KEY_ALIAS }}
  KEYSTORE_KEY_PASSWORD: ${{ secrets.KEYSTORE_KEY_PASSWORD }}
  KEYSTORE_STORE_PASSWORD: ${{ secrets.KEYSTORE_STORE_PASSWORD }}
  
concurrency:
  group: environment-${{ github.ref }}
  cancel-in-progress: true  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
#     - name: Create GitHub Release
#       uses: softprops/action-gh-release@v1
#       with:
#         name: ${{ env.ANDROID_VERSION_NAME }}
#         tag_name: ${{ env.ANDROID_VERSION_NAME }}
#         draft: false
#         prerelease: false
#         files: |
#           app/build/outputs/apk/**/*.apk
#           app/build/outputs/bundle/**/*.aab
          
#      - name: Distribute Artifacts via Firebase
#        run: ./gradlew appDistributionUploadRelease
#        env:
#          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      - name: Create Service Account JSON File
        run: echo '${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_JSON }}' > service_account.json
        
#      - name: Upload Bundle to Google Play Console
#        uses: sokchanbo/android-upload-google-play@v1.0.0
#        with:
#          service-account: service_account.json
#          package-name: org.michaelbel.template
#          release-file: app/build/outputs/bundle/**/*.aab
#          track: internal